import {distanceToSegment,videoPoint,slapValid,multiplier} from './engine.mjs';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),arena=$('arena'),video=$('camera');
const sprite=new Image();sprite.src='assets/ghosts.png';$('ghost-preview').style.backgroundImage='url(assets/ghosts.png)';
const screens=['start-screen','setup-screen','pause-screen','result-screen'];
let phase='home',mode='touch',w=600,h=690,dpr=1,stream=null,worker=null,ready=false,inFlight=false,cameraToken=0,initTimer=0,lastInfer=0,lastVideo=-1,trackingError=false;
let facePoints=[],faceSeen=0,hands=[],previousHands=new Map(),handSeen=0,handCooldown=new Map(),trails=[],ghosts=[],particles=[],popups=[],score=0,streak=0,maxCombo=1,hits=0,misses=0,elapsed=0,lastFrame=0,nextSpawn=0,countdown=0,possessedUntil=0,shake=0;
let sensitivity=2,sound=false,audio=null,pointerStart=null,feedbackTimer=0;
const colors=['#c9ff65','#b8a0ff','#ffaf88'],points=[10,25,40],reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function resize(){const r=arena.getBoundingClientRect();const ow=w,oh=h;w=r.width;h=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);for(const g of ghosts){g.x*=w/ow;g.y*=h/oh;g.startX*=w/ow;g.startY*=h/oh}previousHands.clear()}
new ResizeObserver(resize).observe(arena);
function screen(id){for(const s of screens)$(s).classList.toggle('hidden',s!==id)}
function say(text){$('feedback').textContent=text;$('feedback').style.opacity='1';clearTimeout(feedbackTimer);feedbackTimer=setTimeout(()=>$('feedback').style.opacity='0',900)}
function tone(kind){if(!sound)return;try{audio ||=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type=kind==='hit'?'triangle':'sine';o.frequency.setValueAtTime(kind==='hit'?360+Math.min(streak,12)*24:90,t);o.frequency.exponentialRampToValueAtTime(kind==='hit'?80:42,t+.16);g.gain.setValueAtTime(.12,t);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.start(t);o.stop(t+.21)}catch{}}
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=`Son : ${sound?'ON':'OFF'}`;$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Couper le son':'Activer le son');if(sound)tone('hit')};
$('sensitivity').oninput=e=>{sensitivity=Number(e.target.value);$('sensitivity-value').value=['','Précise','Normale','Facile'][sensitivity]};
function cleanCamera(){cameraToken++;clearTimeout(initTimer);worker?.terminate();worker=null;stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;video.style.display='none';ready=false;inFlight=false;facePoints=[];hands=[];previousHands.clear();handCooldown.clear();faceSeen=0;handSeen=0;trackingError=false;lastVideo=-1}
function home(){cleanCamera();phase='home';mode='touch';screen('start-screen');$('pause').classList.add('hidden');$('session-badge').textContent='CHASSE AUX FANTÔMES';$('tracking').textContent='SELFIE AR / MODE TACTILE';$('feedback').style.opacity='0';ghosts=[];particles=[];popups=[];trails=[];score=0;streak=0;$('score').textContent='0000';$('combo').textContent='×1';$('clock').innerHTML='45<span>s</span>';$('clock').classList.remove('urgent');possessedUntil=0}
function setupError(message){cleanCamera();phase='setup';$('setup-title').textContent='La caméra fait sa timide.';$('setup-message').textContent=message;$('launch').classList.add('hidden');$('face-status').textContent='Essaie le mode tactile en attendant.';$('hand-status').textContent='';screen('setup-screen')}
async function activate(){cleanCamera();mode='camera';phase='setup';screen('setup-screen');$('setup-title').textContent='Réveil des fantômes…';$('setup-message').textContent='Autorise la caméra pour jouer en selfie.';$('launch').classList.add('hidden');$('face-status').textContent='Visage : en attente';$('hand-status').textContent='Main : en attente';const token=cameraToken;
 try{
  if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');
  const cameraPromise=navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480},frameRate:{ideal:24,max:30}},audio:false}).then(acquired=>{if(token!==cameraToken)acquired.getTracks().forEach(t=>t.stop());return acquired});
  const timeout=new Promise((_,reject)=>{initTimer=setTimeout(()=>reject(new Error('permission-timeout')),30000)});
  const acquired=await Promise.race([cameraPromise,timeout]);clearTimeout(initTimer);
  if(token!==cameraToken){acquired.getTracks().forEach(t=>t.stop());return}
  stream=acquired;video.srcObject=stream;await video.play();if(token!==cameraToken)return;video.style.display='block';
  stream.getVideoTracks()[0].onended=()=>{if(mode==='camera'&&phase!=='home')setupError('La caméra a été interrompue. Reviens à l’accueil pour la réactiver.')};
  if(!window.Worker||!window.OffscreenCanvas)throw new Error('unsupported-worker');
  $('setup-message').textContent='Premier lancement : chargement du suivi des gestes. Cela peut prendre quelques secondes.';
  worker=new Worker(new URL('./tracking-worker.js',import.meta.url));
  initTimer=setTimeout(()=>{if(token===cameraToken)setupError('Le suivi des gestes n’a pas pu se charger. Vérifie ta connexion puis réessaie, ou choisis le mode tactile.')},75000);
  worker.onmessage=({data})=>{if(token!==cameraToken)return;if(data.type==='loading')$('setup-message').textContent=data.message;
   if(data.type==='ready'){clearTimeout(initTimer);ready=true;$('setup-title').textContent='Prêt à donner des claques ?';$('setup-message').textContent='Pose ton téléphone. Cadre ton visage et montre ta main, puis lance la chasse.';$('launch').classList.remove('hidden');$('tracking').textContent='MONTRE TA MAIN À LA CAMÉRA'}
   if(data.type==='result'){inFlight=false;processTracking(data)}
   if(data.type==='skipped')inFlight=false;
   if(data.type==='error'&&!trackingError){trackingError=true;setupError('Le suivi des gestes est indisponible sur ce navigateur. Essaie Chrome ou Safari à jour, ou joue au toucher.')}
  };
  worker.onerror=()=>{if(token===cameraToken)setupError('Impossible de charger le suivi des gestes. Vérifie la connexion ou essaie le mode tactile.')};worker.postMessage({type:'init'});
 }catch(e){if(token!==cameraToken)return;const message=e.name==='NotAllowedError'?'L’accès à la caméra a été refusé. Autorise-le dans les réglages du navigateur puis réessaie.':e.name==='NotFoundError'?'Aucune caméra trouvée. Le mode tactile reste disponible.':e.message==='permission-timeout'?'L’autorisation de caméra est restée en attente. Reviens à l’accueil pour réessayer.':'La caméra ou le suivi des gestes n’est pas disponible ici. Ouvre le lien dans ton navigateur, ou joue au toucher.';setupError(message)}
}
$('activate').onclick=activate;$('cancel-setup').onclick=home;
$('demo').onclick=()=>{cleanCamera();mode='touch';start()};$('launch').onclick=()=>{if(ready)start()};
function start(){if(mode==='camera'&&!ready){home();return}score=0;streak=0;maxCombo=1;hits=0;misses=0;elapsed=0;nextSpawn=.15;ghosts=[];particles=[];popups=[];trails=[];previousHands.clear();handCooldown.clear();possessedUntil=0;shake=0;phase='countdown';countdown=3;screen(null);$('pause').classList.add('hidden');$('clock').classList.remove('urgent');$('score').textContent='0000';$('combo').textContent='×1';$('clock').innerHTML='45<span>s</span>';$('session-badge').textContent=mode==='touch'?'MODE TACTILE':'SELFIE AUGMENTÉ';$('tracking').textContent=mode==='touch'?'TOUCHE OU BALAYE LES FANTÔMES':'BALAYE LES FANTÔMES AVEC TA MAIN';tone('hit')}
function pause(){if(phase==='playing'){phase='paused';screen('pause-screen');previousHands.clear();$('pause').classList.add('hidden')}}
function resume(){if(phase==='paused'){phase='playing';screen(null);previousHands.clear();$('pause').classList.remove('hidden')}}
$('pause').onclick=pause;$('resume').onclick=resume;$('quit').onclick=home;$('home').onclick=home;$('again').onclick=()=>{if(mode==='camera'){phase='setup';screen('setup-screen');$('setup-title').textContent='Une autre chasse ?';$('setup-message').textContent='Replace ton visage et ta main dans le cadre.';}else start()};
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(phase==='countdown'){phase='playing';pause()}else pause()}});window.addEventListener('pagehide',cleanCamera);document.addEventListener('keydown',e=>{if(e.key==='Escape')phase==='paused'?resume():pause()});
function finish(){phase='results';screen('result-screen');$('pause').classList.add('hidden');$('final-score').textContent=score;$('final-hits').textContent=hits;$('final-combo').textContent=`×${maxCombo}`;$('final-misses').textContent=misses;$('result-title').textContent=score>=900?'Terreur des fantômes !':score>=400?'Bien frappé !':'Première exorcisation.';$('result-detail').textContent=mode==='camera'?'45 secondes de selfie hanté.':'45 secondes de chasse au toucher.';$('tracking').textContent='CHASSE TERMINÉE';$('clock').innerHTML='0<span>s</span>';ghosts=[];previousHands.clear();hands=[];tone('hit')}
function mapped(p){return videoPoint(p,video.videoWidth||640,video.videoHeight||480,w,h)}
function faceCenter(){if(facePoints.length&&performance.now()-faceSeen<900){const p=mapped(facePoints[1]);return{x:Math.max(w*.28,Math.min(w*.72,p.x)),y:Math.max(h*.3,Math.min(h*.7,p.y))}}return{x:w*.5,y:h*.49}}
function spawn(){const type=Math.random()<.15?2:Math.random()<.35?1:0;const f=faceCenter();const side=Math.random()<.5?-1:1;const x=side<0?w*.12:w*.88;const y=h*(.25+Math.random()*.42);ghosts.push({id:crypto.randomUUID(),type,x,y,startX:x,startY:y,targetX:f.x+side*w*.13,targetY:f.y+(Math.random()-.5)*h*.24,age:0,duration:4.5-Math.min(1.8,elapsed/25)+(type===2?.8:0),radius:Math.min(w*.105,65),hp:type===2?2:1,lastHit:-Infinity,seed:Math.random()*6,flash:0})}
function hit(g,now){if(now-g.lastHit<220)return false;g.lastHit=now;g.hp--;g.flash=.16;shake=reduced?0:4;tone('hit');burst(g.x,g.y,colors[g.type],g.hp>0?8:18);if(g.hp>0){say('Encore une !');return true}g.dead=true;hits++;streak++;const multi=multiplier(streak);maxCombo=Math.max(maxCombo,multi);const gain=points[g.type]*multi;score+=gain;$('score').textContent=String(score).padStart(4,'0');$('combo').textContent=`×${multi}`;popups.push({x:g.x,y:g.y,text:`+${gain}`,age:0,color:colors[g.type]});if(streak%4===0)say(`COMBO ×${multi}`);return true}
function slap(a,b,now,byHand=false){if(phase!=='playing')return false;trails.push({a,b,age:0,color:byHand?'#c9ff65':'#ffffff'});let landed=false;for(const g of ghosts)if(!g.dead&&distanceToSegment(g,a,b)<g.radius+Math.min(w*.04,24))landed=hit(g,now)||landed;ghosts=ghosts.filter(g=>!g.dead);return landed}
function burst(x,y,color,n){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=60+Math.random()*170;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,age:0,life:.35+Math.random()*.3,color,r:2+Math.random()*4})}}
function possess(g){misses++;streak=0;$('combo').textContent='×1';possessedUntil=performance.now()+2200;tone('miss');say('POSSÉDÉ !');burst(g.x,g.y,'#b8a0ff',12)}
function processTracking(data){if(!['playing','setup','countdown'].includes(phase))return;const now=performance.now();hands=data.hands.map(landmarks=>({landmarks,point:mapped(landmarks[9])}));if(hands.length)handSeen=now;if(data.face!==null){facePoints=data.face;if(facePoints.length)faceSeen=now}if(phase==='setup'){$('face-status').textContent=facePoints.length?'Visage : détecté ✓':'Visage : cherche le cadre';$('hand-status').textContent=hands.length?'Main : détectée ✓':'Main : montre ta paume'}
 $('tracking').textContent=hands.length?'MAIN DÉTECTÉE / À TOI DE JOUER':'MONTRE TA MAIN À LA CAMÉRA';const used=new Set();hands.forEach((hand,index)=>{let id=index,best=Infinity;for(const [key,old]of previousHands)if(!used.has(key)){const d=Math.hypot(old.point.x-hand.point.x,old.point.y-hand.point.y);if(d<best){best=d;id=key}}used.add(id);const old=previousHands.get(id);if(old&&phase==='playing'&&slapValid(old.point,hand.point,data.timestamp-old.time,w,sensitivity)&&now-(handCooldown.get(id)||0)>220){slap(old.point,hand.point,now,true);handCooldown.set(id,now)}previousHands.set(id,{point:hand.point,time:data.timestamp})});for(const [id,p]of previousHands)if(data.timestamp-p.time>200)previousHands.delete(id)
}
async function infer(now){if(!worker||!ready||inFlight||video.readyState<2||!['setup','playing','countdown'].includes(phase)||now-lastInfer<80||video.currentTime===lastVideo)return;inFlight=true;lastInfer=now;lastVideo=video.currentTime;const current=worker;try{const bitmap=await createImageBitmap(video,{resizeWidth:640,resizeHeight:Math.round(640*video.videoHeight/video.videoWidth)});if(current!==worker){bitmap.close();inFlight=false;return}current.postMessage({type:'frame',bitmap,timestamp:now,width:video.videoWidth,height:video.videoHeight},[bitmap])}catch{inFlight=false;setupError('Le navigateur ne peut pas analyser la caméra. Essaie le mode tactile.')}
}
function point(e){const r=arena.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
arena.addEventListener('pointerdown',e=>{if(phase!=='playing'||mode!=='touch'||e.target.closest('button'))return;e.preventDefault();arena.setPointerCapture(e.pointerId);pointerStart=point(e);slap(pointerStart,pointerStart,performance.now())});arena.addEventListener('pointermove',e=>{if(pointerStart&&phase==='playing'&&mode==='touch'){const p=point(e);slap(pointerStart,p,performance.now());pointerStart=p}});arena.addEventListener('pointerup',()=>pointerStart=null);arena.addEventListener('pointercancel',()=>pointerStart=null);
function drawGhost(g,now){const side=sprite.width/3;const size=g.radius*2.65;ctx.save();ctx.translate(g.x,g.y);ctx.rotate(Math.sin(now/450+g.seed)*.1);if(g.flash>0){ctx.scale(1.18,.9);ctx.globalAlpha=.8}if(sprite.complete&&sprite.naturalWidth)ctx.drawImage(sprite,g.type*side,0,side,sprite.height,-size/2,-size*.68,size,size*1.8);ctx.restore();if(g.type===2){ctx.fillStyle=g.hp===2?'#ffaf88':'#ffaf8870';ctx.beginPath();ctx.arc(g.x-5,g.y+g.radius*.85,3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffaf88';ctx.beginPath();ctx.arc(g.x+5,g.y+g.radius*.85,3,0,Math.PI*2);ctx.fill()}}
function eyeGlow(p,width,angle){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(angle);ctx.shadowBlur=24;ctx.shadowColor='#c9ff65';ctx.fillStyle='#c9ff65';ctx.beginPath();ctx.ellipse(0,0,width,width*.43,0,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#344723';ctx.beginPath();ctx.ellipse(0,0,width*.18,width*.4,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawPossession(now){if(now>possessedUntil)return;const strength=Math.min(1,(possessedUntil-now)/400);ctx.fillStyle=`rgba(120,55,180,${.16*strength})`;ctx.fillRect(0,0,w,h);if(facePoints.length&&now-faceSeen<900){const left=mapped(facePoints[33]),right=mapped(facePoints[263]);const midL=mapped(facePoints[159]),midR=mapped(facePoints[386]);const width=Math.max(6,Math.hypot(right.x-left.x,right.y-left.y)*.12);const a=Math.atan2(right.y-left.y,right.x-left.x);ctx.globalAlpha=strength;eyeGlow(midL,width,a);eyeGlow(midR,width,a);ctx.globalAlpha=1}}
function draw(now,dt){ctx.clearRect(0,0,w,h);ctx.save();if(shake>0){ctx.translate(Math.random()*shake-shake/2,Math.random()*shake-shake/2);shake=Math.max(0,shake-dt*30)}
 if(mode==='touch'&&phase!=='home'){ctx.fillStyle='#b8a0ff08';for(let i=0;i<22;i++){const x=(Math.sin(i*31)*.5+.5)*w,y=(i*83+now*.01)%h;ctx.beginPath();ctx.arc(x,y,1.5,0,Math.PI*2);ctx.fill()}}
 for(const g of ghosts)drawGhost(g,now);for(const p of particles){p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=120*dt;ctx.globalAlpha=Math.max(0,1-p.age/p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}particles=particles.filter(p=>p.age<p.life);ctx.globalAlpha=1;
 for(const t of trails){t.age+=dt;ctx.globalAlpha=Math.max(0,1-t.age/.2);ctx.strokeStyle=t.color;ctx.lineWidth=8;ctx.lineCap='round';ctx.shadowColor=t.color;ctx.shadowBlur=16;ctx.beginPath();ctx.moveTo(t.a.x,t.a.y);ctx.lineTo(t.b.x,t.b.y);ctx.stroke()}ctx.shadowBlur=0;ctx.globalAlpha=1;trails=trails.filter(t=>t.age<.2);
 for(const p of popups){p.age+=dt;ctx.globalAlpha=Math.max(0,1-p.age/.7);ctx.fillStyle=p.color;ctx.font='700 26px "Space Grotesk",sans-serif';ctx.textAlign='center';ctx.fillText(p.text,p.x,p.y-p.age*70)}popups=popups.filter(p=>p.age<.7);ctx.globalAlpha=1;
 if(mode==='camera'&&now-handSeen<250&&['playing','setup'].includes(phase)){for(const hand of hands){ctx.strokeStyle='#c9ff65';ctx.lineWidth=2;ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(hand.point.x,hand.point.y,14,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}}
 drawPossession(now);if(phase==='countdown'){ctx.fillStyle='#140f2360';ctx.fillRect(0,0,w,h);ctx.fillStyle='#c9ff65';ctx.font='700 120px "Space Grotesk",sans-serif';ctx.textAlign='center';ctx.fillText(Math.max(1,Math.ceil(countdown)),w/2,h/2+35)}ctx.restore()}
function loop(now){const clockDt=Math.max(0,(now-lastFrame)/1000||0),dt=Math.min(clockDt,.075);lastFrame=now;if(!document.hidden)infer(now);
 if(phase==='countdown'){countdown-=dt;if(countdown<=0){phase='playing';$('pause').classList.remove('hidden');say(mode==='camera'?'À TES MAINS !':'À TOI DE JOUER !')}}
 if(phase==='playing'){elapsed+=clockDt;const remaining=Math.max(0,Math.ceil(45-elapsed));$('clock').innerHTML=`${remaining}<span>s</span>`;$('clock').classList.toggle('urgent',remaining<=10);if(elapsed>=45)finish();else{if(elapsed>=nextSpawn&&ghosts.length<6){spawn();nextSpawn=elapsed+Math.max(.6,1.25-elapsed*.012)}for(const g of ghosts){g.age+=dt;g.flash=Math.max(0,g.flash-dt);const f=faceCenter(),side=g.startX<w/2?-1:1;g.targetX=f.x+side*w*.13;g.targetY=f.y+Math.sin(g.seed)*h*.1;const p=Math.min(1,g.age/g.duration);g.x=g.startX+(g.targetX-g.startX)*p+(g.type===1?Math.sin(g.age*5+g.seed)*w*.08:Math.sin(g.age*3+g.seed)*8);g.y=g.startY+(g.targetY-g.startY)*p+Math.sin(g.age*3+g.seed)*12;if(p>=1){possess(g);g.dead=true}}ghosts=ghosts.filter(g=>!g.dead)}}
 if(phase==='home'&&sprite.complete&&sprite.naturalWidth){const mock=[{type:0,x:w*.17,y:h*.7,radius:Math.min(w*.065,38),seed:2,flash:0},{type:1,x:w*.85,y:h*.8,radius:Math.min(w*.06,35),seed:0,flash:0}];ctx.clearRect(0,0,w,h);for(const g of mock)drawGhost({...g,y:g.y+(reduced?0:Math.sin(now/850+g.seed)*10)},now)}else draw(now,dt);requestAnimationFrame(loop)
}
requestAnimationFrame(loop);
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const definitions=[{name:'read_ghost_slap_state',title:'Lire la partie Ghost Slap',description:'Lire le mode, la phase et le score de la chasse en cours.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Aucun paramètre attendu.');return{phase,mode,score,hits,possessions:misses,remaining:Math.max(0,45-elapsed)}}},{name:'start_ghost_slap_touch_game',title:'Démarrer une chasse tactile',description:'Démarrer une nouvelle partie de 45 secondes au toucher. Ne demande pas la caméra.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Aucun paramètre attendu.');if(['playing','paused','countdown','setup'].includes(phase))throw new Error('Une partie ou une préparation est déjà en cours.');cleanCamera();mode='touch';start();return{phase,mode,duration:45}}}];for(const tool of definitions)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
